services:
  db:
    image: postgres:15-alpine
    container_name: short-url-db
    restart: always
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_DB: short_url_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: short-url-api
    restart: always
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://dbUser:dbPassword@db:5432/short_url_db # overwrites the .env file for the correct Docker host
    depends_on:
      - db

volumes:
  postgres_data:
